import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/trpc/react";
import StoreProvider from "@/providers/StoreProvider";
import "@/styles/globals.css";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <TRPCReactProvider>
            <StoreProvider>
              {children}
            </StoreProvider>
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
